### PR TITLE
Updated to support Spanish

### PR DESCRIPTION
**Pull request by ruben0909**
- Updated to support Spanish
- Transpiled in Windows
- Minos json format Fix

### CODE REVIEW

**Comment by m0ngr31** [comment]
It looks like you might be using a typescript config/version or something based on how the JS is getting generated. If you wouldn't mind ripping out the generated JS files and I can build them myself. Just for better compatibility.

**Comment by m0ngr31** [comment]
Also, please add support for `es-MX` too.

**Comment by m0ngr31** [comment]
I created a PR for you to approve on your branch. Should solve the things I talked about: https://github.com/ruben0909/lexigram-cli/pull/1

**Comment by ruben0909** [comment]
I'm not pretty sure about if everithing is ok right now, 
I think you have to resolve these conflicts preserving these files(Created in your PR). 
I add you as a collaborator in my fork.
Feel free to change/edit or whatever you want about this code in your/my repository.
I have to learn a lot about use Git. :)
Thank you.

**Review by m0ngr31 — APPROVED** [review]

**Pull request merged**
